DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
        CREATE SCHEMA core;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS core.__ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

-- core.schema_script_history — docs/database/schema-core.md §9.1. KHÔNG phải entity EF (như
-- __ef_migrations_history ở trên) — bảng này trả lời "database đã chạy những script nào" cho CON
-- NGƯỜI, tạo một lần ở đây và tồn tại độc lập với lịch sử migration của EF.
CREATE TABLE IF NOT EXISTS core.schema_script_history (
    id bigint GENERATED ALWAYS AS IDENTITY,
    script_name varchar(200) NOT NULL,
    checksum_sha256 char(64) NOT NULL,
    owner varchar(50) NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now(),
    applied_by varchar(100) NOT NULL,
    duration_ms integer NULL,
    note text NULL,
    CONSTRAINT pk_schema_script_history PRIMARY KEY (id),
    CONSTRAINT ux_schema_script_history_script_name UNIQUE (script_name)
);

CREATE INDEX IF NOT EXISTS ix_schema_script_history_applied_at
    ON core.schema_script_history (applied_at DESC);

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
            CREATE SCHEMA core;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.data_protection_key (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        friendly_name text,
        xml text,
        CONSTRAINT pk_data_protection_key PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.permission_resource (
        id uuid NOT NULL,
        key character varying(100) NOT NULL,
        name_key character varying(200) NOT NULL,
        module_key character varying(100),
        display_order integer NOT NULL DEFAULT 0,
        created_by character varying(100),
        updated_by character varying(100),
        created_at timestamp with time zone,
        updated_at timestamp with time zone,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_permission_resource PRIMARY KEY (id),
        CONSTRAINT uq_permission_resource_key UNIQUE (key)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.tenant (
        id uuid NOT NULL,
        code character varying(50) NOT NULL,
        name character varying(200) NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        is_system boolean NOT NULL DEFAULT FALSE,
        created_by character varying(100),
        updated_by character varying(100),
        created_at timestamp with time zone,
        updated_at timestamp with time zone,
        CONSTRAINT pk_tenant PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.permission (
        id uuid NOT NULL,
        code character varying(150) NOT NULL,
        resource_key character varying(100) NOT NULL,
        action character varying(50) NOT NULL,
        name_key character varying(200) NOT NULL,
        is_system boolean NOT NULL DEFAULT FALSE,
        display_order integer NOT NULL DEFAULT 0,
        created_by character varying(100),
        updated_by character varying(100),
        created_at timestamp with time zone,
        updated_at timestamp with time zone,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_permission PRIMARY KEY (id),
        CONSTRAINT fk_permission_resource_key FOREIGN KEY (resource_key) REFERENCES core.permission_resource (key) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.app_role (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        created_by character varying(100),
        updated_by character varying(100),
        created_at timestamp with time zone,
        updated_at timestamp with time zone,
        description character varying(500),
        is_system boolean NOT NULL DEFAULT FALSE,
        name character varying(256),
        normalized_name character varying(256),
        concurrency_stamp text,
        CONSTRAINT pk_app_role PRIMARY KEY (id),
        CONSTRAINT fk_app_role_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.app_user (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        created_by character varying(100),
        updated_by character varying(100),
        created_at timestamp with time zone,
        updated_at timestamp with time zone,
        full_name character varying(200) NOT NULL,
        must_change_password boolean NOT NULL DEFAULT TRUE,
        preferred_language character varying(10),
        is_system_operator boolean NOT NULL DEFAULT FALSE,
        has_permission_bypass boolean NOT NULL DEFAULT FALSE,
        locked_by_admin boolean NOT NULL DEFAULT FALSE,
        user_name character varying(256),
        normalized_user_name character varying(256),
        email character varying(256),
        normalized_email character varying(256),
        email_confirmed boolean NOT NULL,
        password_hash text,
        security_stamp text,
        concurrency_stamp text,
        phone_number character varying(20),
        phone_number_confirmed boolean NOT NULL,
        two_factor_enabled boolean NOT NULL,
        lockout_end timestamp with time zone,
        lockout_enabled boolean NOT NULL,
        access_failed_count integer NOT NULL,
        CONSTRAINT pk_app_user PRIMARY KEY (id),
        CONSTRAINT ck_app_user_privilege_flags_exclusive CHECK (NOT (has_permission_bypass AND is_system_operator)),
        CONSTRAINT fk_app_user_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.menu_item (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        code character varying(100) NOT NULL,
        label_key character varying(200) NOT NULL,
        icon character varying(50),
        route character varying(200),
        parent_id uuid,
        display_order integer NOT NULL DEFAULT 0,
        required_permission_id uuid,
        module_key character varying(100),
        created_by character varying(100),
        updated_by character varying(100),
        created_at timestamp with time zone,
        updated_at timestamp with time zone,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_menu_item PRIMARY KEY (id),
        CONSTRAINT ck_menu_item_not_self_parent CHECK (parent_id IS NULL OR parent_id <> id),
        CONSTRAINT fk_menu_item_parent_id FOREIGN KEY (parent_id) REFERENCES core.menu_item (id) ON DELETE RESTRICT,
        CONSTRAINT fk_menu_item_required_permission_id FOREIGN KEY (required_permission_id) REFERENCES core.permission (id) ON DELETE RESTRICT,
        CONSTRAINT fk_menu_item_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.app_role_claim (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id uuid NOT NULL,
        role_id uuid NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_app_role_claim PRIMARY KEY (id),
        CONSTRAINT fk_app_role_claim_role_id FOREIGN KEY (role_id) REFERENCES core.app_role (id) ON DELETE CASCADE,
        CONSTRAINT fk_app_role_claim_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.role_permission (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        role_id uuid NOT NULL,
        permission_id uuid NOT NULL,
        created_by character varying(100),
        updated_by character varying(100),
        created_at timestamp with time zone,
        updated_at timestamp with time zone,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_role_permission PRIMARY KEY (id),
        CONSTRAINT fk_role_permission_permission_id FOREIGN KEY (permission_id) REFERENCES core.permission (id) ON DELETE CASCADE,
        CONSTRAINT fk_role_permission_role_id FOREIGN KEY (role_id) REFERENCES core.app_role (id) ON DELETE CASCADE,
        CONSTRAINT fk_role_permission_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.app_user_claim (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id uuid NOT NULL,
        user_id uuid NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT pk_app_user_claim PRIMARY KEY (id),
        CONSTRAINT fk_app_user_claim_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT,
        CONSTRAINT fk_app_user_claim_user_id FOREIGN KEY (user_id) REFERENCES core.app_user (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.app_user_login (
        login_provider text NOT NULL,
        provider_key text NOT NULL,
        tenant_id uuid NOT NULL,
        provider_display_name text,
        user_id uuid NOT NULL,
        CONSTRAINT pk_app_user_login PRIMARY KEY (tenant_id, login_provider, provider_key),
        CONSTRAINT fk_app_user_login_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT,
        CONSTRAINT fk_app_user_login_user_id FOREIGN KEY (user_id) REFERENCES core.app_user (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.app_user_role (
        user_id uuid NOT NULL,
        role_id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        CONSTRAINT pk_app_user_role PRIMARY KEY (user_id, role_id),
        CONSTRAINT fk_app_user_role_role_id FOREIGN KEY (role_id) REFERENCES core.app_role (id) ON DELETE CASCADE,
        CONSTRAINT fk_app_user_role_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT,
        CONSTRAINT fk_app_user_role_user_id FOREIGN KEY (user_id) REFERENCES core.app_user (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.app_user_token (
        user_id uuid NOT NULL,
        login_provider text NOT NULL,
        name text NOT NULL,
        tenant_id uuid NOT NULL,
        value text,
        CONSTRAINT pk_app_user_token PRIMARY KEY (user_id, login_provider, name),
        CONSTRAINT fk_app_user_token_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT,
        CONSTRAINT fk_app_user_token_user_id FOREIGN KEY (user_id) REFERENCES core.app_user (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE TABLE core.menu_item_role (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        menu_item_id uuid NOT NULL,
        role_id uuid NOT NULL,
        created_by character varying(100),
        updated_by character varying(100),
        created_at timestamp with time zone,
        updated_at timestamp with time zone,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_menu_item_role PRIMARY KEY (id),
        CONSTRAINT fk_menu_item_role_menu_item_id FOREIGN KEY (menu_item_id) REFERENCES core.menu_item (id) ON DELETE CASCADE,
        CONSTRAINT fk_menu_item_role_role_id FOREIGN KEY (role_id) REFERENCES core.app_role (id) ON DELETE CASCADE,
        CONSTRAINT fk_menu_item_role_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenant (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON core.app_role (tenant_id, normalized_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_role_claim_role_id ON core.app_role_claim (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_role_claim_tenant_role_id ON core.app_role_claim (tenant_id, role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX "EmailIndex" ON core.app_user (tenant_id, normalized_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON core.app_user (tenant_id, normalized_user_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_user_claim_tenant_user_id ON core.app_user_claim (tenant_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_user_claim_user_id ON core.app_user_claim (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_user_login_tenant_user_id ON core.app_user_login (tenant_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_user_login_user_id ON core.app_user_login (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_user_role_role_id ON core.app_user_role (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_user_role_tenant_role_id ON core.app_user_role (tenant_id, role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_app_user_token_tenant_id ON core.app_user_token (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_menu_item_parent_id ON core.menu_item (parent_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_menu_item_required_permission_id ON core.menu_item (required_permission_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_menu_item_tenant_parent_order ON core.menu_item (tenant_id, parent_id, display_order);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX ux_menu_item_tenant_code_active ON core.menu_item (tenant_id, code) WHERE is_deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_menu_item_role_menu_item_id ON core.menu_item_role (menu_item_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_menu_item_role_role_id ON core.menu_item_role (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_menu_item_role_tenant_role_id ON core.menu_item_role (tenant_id, role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX ux_menu_item_role_tenant_item_role_active ON core.menu_item_role (tenant_id, menu_item_id, role_id) WHERE is_deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_permission_resource_key_display_order ON core.permission (resource_key, display_order);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX ux_permission_code_active ON core.permission (code) WHERE is_deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_permission_resource_module_key ON core.permission_resource (module_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_role_permission_permission_id ON core.role_permission (permission_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_role_permission_role_id ON core.role_permission (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE INDEX ix_role_permission_tenant_perm_role ON core.role_permission (tenant_id, permission_id, role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX ux_role_permission_tenant_role_perm_active ON core.role_permission (tenant_id, role_id, permission_id) WHERE is_deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX uq_tenant_code ON core.tenant (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    CREATE UNIQUE INDEX ux_tenant_is_system ON core.tenant (is_system) WHERE is_system;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260917043348_TaoLuocDoCore') THEN
    INSERT INTO core.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260917043348_TaoLuocDoCore', '10.0.12');
    END IF;
END $EF$;

-- Ghi nhận đã áp — docs/database/script-runbook.md §3.1. Checksum tính trên nội dung file NGAY
-- TRƯỚC khối này (§3.2: grep -abm1 '^-- Ghi nhận đã áp' rồi head -c "$offset" | sha256sum).
INSERT INTO core.schema_script_history (script_name, checksum_sha256, owner, applied_by, note)
VALUES ('0001__core__initial.sql',
        '2be447a3aa4d1c1b4add8716d9b0a2ed2f71fc88237de82f369cdf20133123e7',
        'core',
        current_user,
        NULL)
ON CONFLICT (script_name) DO NOTHING;

COMMIT;

